version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands: 
      - cd p1-react-redux/
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'p1-react-redux/build'